run:
  timeout: 5m
  tests: true

linters:
  enable:
    - bodyclose
    - errcheck
    - errorlint
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

linters-settings:
  errorlint:
    errorf: true
    asserts: true
    comparison: true

issues:
  exclude-dirs:
    - internal/visualize/testdata
