run:
  timeout: 5m
  tests: true

linters:
  enable:
    - bodyclose
    - errcheck
    - errorlint
    - gosimple
    - govet
    - ineffassign
    - revive
    - staticcheck
    - unused

linters-settings:
  errorlint:
    errorf: true
    asserts: true
    comparison: true
  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
        disabled: true
      - name: increment-decrement
      - name: var-naming
      - name: package-comments
        disabled: true
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
        disabled: true
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unreachable-code
      - name: redefines-builtin-id

issues:
  exclude-dirs:
    - internal/visualize/testdata
