#!/bin/bash
# Build export.tar.gz and a small HTML landing page with manifest summary.
set -euo pipefail

OUTPUT_DIR="${1:?output dir}"
WWW_DIR="${2:?www dir}"
MANIFEST="${OUTPUT_DIR}/manifest.json"
INDEX="${WWW_DIR}/index.html"
ARCHIVE="${WWW_DIR}/export.tar.gz"

mkdir -p "${WWW_DIR}"

if [[ -d "${OUTPUT_DIR}" ]] && [[ -n "$(ls -A "${OUTPUT_DIR}" 2>/dev/null || true)" ]]; then
  tar -czf "${ARCHIVE}" -C "${OUTPUT_DIR}" .
else
  echo "warning: export directory is empty — skipping tarball" >&2
fi

summary_products="-"
summary_backends="-"
summary_exported="-"
summary_admin="-"
summary_warnings="0"
summary_incomplete="false"

if [[ -f "${MANIFEST}" ]]; then
  if command -v python3 >/dev/null 2>&1; then
    read -r summary_products summary_backends summary_exported summary_admin summary_warnings summary_incomplete <<EOF
$(python3 - "${MANIFEST}" <<'PY'
import json, sys
with open(sys.argv[1], encoding="utf-8") as f:
    m = json.load(f)
print(
    m.get("product_count", "-"),
    m.get("backend_count", "-"),
    m.get("exported_at", "-"),
    m.get("admin_url", "-"),
    len(m.get("warnings") or []),
    str(bool(m.get("incomplete"))).lower(),
)
PY
)
EOF
  else
    summary_exported="$(grep -o '"exported_at"[[:space:]]*:[[:space:]]*"[^"]*"' "${MANIFEST}" | head -1 | sed 's/.*"\([^"]*\)"$/\1/' || true)"
    summary_admin="$(grep -o '"admin_url"[[:space:]]*:[[:space:]]*"[^"]*"' "${MANIFEST}" | head -1 | sed 's/.*"\([^"]*\)"$/\1/' || true)"
  fi
fi

cat > "${INDEX}" <<HTML
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>3scale tenant export</title>
  <style>
    body { font-family: system-ui, sans-serif; margin: 2rem; line-height: 1.5; max-width: 52rem; }
    h1 { margin-bottom: 0.25rem; }
    .meta { color: #444; margin-bottom: 1.5rem; }
    ul { padding-left: 1.25rem; }
    a { color: #0066cc; }
    code { background: #f4f4f4; padding: 0.1rem 0.35rem; border-radius: 3px; }
    .warn { color: #a33; }
  </style>
</head>
<body>
  <h1>3scale tenant export</h1>
  <p class="meta">
    Admin URL: <code>${summary_admin}</code><br>
    Exported at: <code>${summary_exported}</code><br>
    Products: <strong>${summary_products}</strong> · Backends: <strong>${summary_backends}</strong>
  </p>
  <ul>
    <li><a href="export.tar.gz">Download full export (<code>export.tar.gz</code>)</a></li>
    <li><a href="data/">Browse export tree (<code>manifest.json</code>, products, backends, …)</a></li>
    <li><a href="data/manifest.json">manifest.json</a></li>
  </ul>
HTML

if [[ "${summary_incomplete}" == "true" ]] || [[ "${summary_warnings}" != "0" ]]; then
  cat >> "${INDEX}" <<HTML
  <p class="warn">Export incomplete or had ${summary_warnings} warning(s). Review <a href="data/manifest.json">manifest.json</a> before migration.</p>
HTML
fi

cat >> "${INDEX}" <<'HTML'
  <p><small>Generated by threescale-export OpenShift image (Red Hat toolbox + nginx).</small></p>
</body>
</html>
HTML
